/**
 * Globally significant military installations — static reference data.
 * Sources: publicly available open-source intelligence (Wikipedia, official DoD/NATO
 * fact sheets, Jane's, CSIS, think-tank reports).
 *
 * Coordinates are approximate centroid values suitable for map markers.
 * This file has zero runtime dependencies.
 */

export interface MilitaryInstallation {
  id: string;
  name: string;
  country: string;
  countryCode: string; // ISO Alpha-2
  lat: number;
  lon: number;
  branch: 'army' | 'navy' | 'air_force' | 'marines' | 'space_force' | 'multi' | 'nato' | 'russian' | 'chinese' | 'other';
  type: 'base' | 'fort' | 'station' | 'camp' | 'airfield' | 'naval_base' | 'command' | 'installation';
}

export const MILITARY_INSTALLATIONS: MilitaryInstallation[] = [
  // ── US DOMESTIC ──────────────────────────────────────────────────────────────
  {
    id: 'fort-liberty',
    name: 'Fort Liberty (Bragg)',
    country: 'United States',
    countryCode: 'US',
    lat: 35.1396,
    lon: -79.0061,
    branch: 'army',
    type: 'fort',
  },
  {
    id: 'fort-wainwright',
    name: 'Fort Wainwright',
    country: 'United States',
    countryCode: 'US',
    lat: 64.8308,
    lon: -147.6614,
    branch: 'army',
    type: 'fort',
  },
  {
    id: 'fort-bliss',
    name: 'Fort Bliss',
    country: 'United States',
    countryCode: 'US',
    lat: 31.8127,
    lon: -106.4011,
    branch: 'army',
    type: 'fort',
  },
  {
    id: 'fort-campbell',
    name: 'Fort Campbell',
    country: 'United States',
    countryCode: 'US',
    lat: 36.6590,
    lon: -87.4769,
    branch: 'army',
    type: 'fort',
  },
  {
    id: 'camp-pendleton',
    name: 'Camp Pendleton',
    country: 'United States',
    countryCode: 'US',
    lat: 33.3856,
    lon: -117.5634,
    branch: 'marines',
    type: 'camp',
  },
  {
    id: 'langley-afb',
    name: 'Joint Base Langley-Eustis',
    country: 'United States',
    countryCode: 'US',
    lat: 37.0821,
    lon: -76.3601,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'edwards-afb',
    name: 'Edwards Air Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 34.9054,
    lon: -117.8836,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'nellis-afb',
    name: 'Nellis Air Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 36.2375,
    lon: -115.0342,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'wright-patterson-afb',
    name: 'Wright-Patterson AFB',
    country: 'United States',
    countryCode: 'US',
    lat: 39.8261,
    lon: -84.0503,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'offutt-afb',
    name: 'Offutt Air Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 41.1183,
    lon: -95.9124,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'minot-afb',
    name: 'Minot Air Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 48.4157,
    lon: -101.3578,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'whiteman-afb',
    name: 'Whiteman Air Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 38.7272,
    lon: -93.5483,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'barksdale-afb',
    name: 'Barksdale Air Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 32.5018,
    lon: -93.6626,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'dyess-afb',
    name: 'Dyess Air Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 32.4208,
    lon: -99.8546,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'malmstrom-afb',
    name: 'Malmstrom Air Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 47.5053,
    lon: -111.1871,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'vandenberg-sfb',
    name: 'Vandenberg Space Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 34.7420,
    lon: -120.5724,
    branch: 'space_force',
    type: 'base',
  },
  {
    id: 'peterson-sfb',
    name: 'Peterson Space Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 38.8226,
    lon: -104.7007,
    branch: 'space_force',
    type: 'base',
  },
  {
    id: 'schriever-sfb',
    name: 'Schriever Space Force Base',
    country: 'United States',
    countryCode: 'US',
    lat: 38.8034,
    lon: -104.5253,
    branch: 'space_force',
    type: 'base',
  },
  {
    id: 'naval-station-norfolk',
    name: 'Naval Station Norfolk',
    country: 'United States',
    countryCode: 'US',
    lat: 36.9455,
    lon: -76.3300,
    branch: 'navy',
    type: 'naval_base',
  },
  {
    id: 'naval-station-san-diego',
    name: 'Naval Station San Diego',
    country: 'United States',
    countryCode: 'US',
    lat: 32.6852,
    lon: -117.1219,
    branch: 'navy',
    type: 'naval_base',
  },
  {
    id: 'pearl-harbor',
    name: 'Joint Base Pearl Harbor-Hickam',
    country: 'United States',
    countryCode: 'US',
    lat: 21.3450,
    lon: -157.9700,
    branch: 'multi',
    type: 'naval_base',
  },
  {
    id: 'nas-pensacola',
    name: 'NAS Pensacola',
    country: 'United States',
    countryCode: 'US',
    lat: 30.3526,
    lon: -87.3188,
    branch: 'navy',
    type: 'naval_base',
  },
  {
    id: 'mcb-quantico',
    name: 'Marine Corps Base Quantico',
    country: 'United States',
    countryCode: 'US',
    lat: 38.5220,
    lon: -77.3622,
    branch: 'marines',
    type: 'base',
  },
  // ── US OVERSEAS ──────────────────────────────────────────────────────────────
  {
    id: 'camp-humphreys',
    name: 'Camp Humphreys',
    country: 'South Korea',
    countryCode: 'KR',
    lat: 36.9716,
    lon: 127.0299,
    branch: 'army',
    type: 'camp',
  },
  {
    id: 'kadena-ab',
    name: 'Kadena Air Base',
    country: 'Japan',
    countryCode: 'JP',
    lat: 26.3522,
    lon: 127.7689,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'yokota-ab',
    name: 'Yokota Air Base',
    country: 'Japan',
    countryCode: 'JP',
    lat: 35.7485,
    lon: 139.3484,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'misawa-ab',
    name: 'Misawa Air Base',
    country: 'Japan',
    countryCode: 'JP',
    lat: 40.7033,
    lon: 141.3683,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'camp-zama',
    name: 'Camp Zama',
    country: 'Japan',
    countryCode: 'JP',
    lat: 35.4892,
    lon: 139.3952,
    branch: 'army',
    type: 'camp',
  },
  {
    id: 'ramstein-ab',
    name: 'Ramstein Air Base',
    country: 'Germany',
    countryCode: 'DE',
    lat: 49.4370,
    lon: 7.6000,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'spangdahlem-ab',
    name: 'Spangdahlem Air Base',
    country: 'Germany',
    countryCode: 'DE',
    lat: 50.1256,
    lon: 6.6925,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'raf-lakenheath',
    name: 'RAF Lakenheath',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 52.4093,
    lon: 0.5600,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'raf-mildenhall',
    name: 'RAF Mildenhall',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 52.3619,
    lon: 0.4864,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'incirlik-ab',
    name: 'Incirlik Air Base',
    country: 'Turkey',
    countryCode: 'TR',
    lat: 37.0021,
    lon: 35.4264,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'al-udeid-ab',
    name: 'Al Udeid Air Base',
    country: 'Qatar',
    countryCode: 'QA',
    lat: 25.1173,
    lon: 51.3150,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'diego-garcia',
    name: 'Diego Garcia',
    country: 'British Indian Ocean Territory',
    countryCode: 'IO',
    lat: -7.3195,
    lon: 72.4104,
    branch: 'multi',
    type: 'base',
  },
  {
    id: 'guantanamo-bay',
    name: 'Guantanamo Bay Naval Station',
    country: 'Cuba',
    countryCode: 'CU',
    lat: 19.9069,
    lon: -75.1000,
    branch: 'navy',
    type: 'naval_base',
  },

  // ── NATO / EUROPEAN ──────────────────────────────────────────────────────────
  {
    id: 'nato-hq',
    name: 'NATO Headquarters',
    country: 'Belgium',
    countryCode: 'BE',
    lat: 50.8807,
    lon: 4.4202,
    branch: 'nato',
    type: 'command',
  },
  {
    id: 'shape-mons',
    name: 'SHAPE (Supreme HQ Allied Powers Europe)',
    country: 'Belgium',
    countryCode: 'BE',
    lat: 50.4455,
    lon: 3.8727,
    branch: 'nato',
    type: 'command',
  },
  {
    id: 'jfc-brunssum',
    name: 'JFC Brunssum',
    country: 'Netherlands',
    countryCode: 'NL',
    lat: 50.9451,
    lon: 5.9792,
    branch: 'nato',
    type: 'command',
  },
  {
    id: 'jfc-naples',
    name: 'JFC Naples',
    country: 'Italy',
    countryCode: 'IT',
    lat: 40.6636,
    lon: 14.2080,
    branch: 'nato',
    type: 'command',
  },
  {
    id: 'decimomannu-ab',
    name: 'Decimomannu Air Base',
    country: 'Italy',
    countryCode: 'IT',
    lat: 39.3544,
    lon: 8.9722,
    branch: 'nato',
    type: 'airfield',
  },
  {
    id: 'aviano-ab',
    name: 'Aviano Air Base',
    country: 'Italy',
    countryCode: 'IT',
    lat: 46.0319,
    lon: 12.5965,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'nas-sigonella',
    name: 'NAS Sigonella',
    country: 'Italy',
    countryCode: 'IT',
    lat: 37.4017,
    lon: 14.9222,
    branch: 'navy',
    type: 'naval_base',
  },
  {
    id: 'raf-fairford',
    name: 'RAF Fairford',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.6819,
    lon: -1.7900,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'raf-brize-norton',
    name: 'RAF Brize Norton',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.7497,
    lon: -1.5836,
    branch: 'air_force',
    type: 'base',
  },
  {
    id: 'bardufoss-ab',
    name: 'Bardufoss Air Base',
    country: 'Norway',
    countryCode: 'NO',
    lat: 69.0578,
    lon: 18.5404,
    branch: 'nato',
    type: 'airfield',
  },
  {
    id: 'grafenwöhr',
    name: 'Grafenwöhr Training Area',
    country: 'Germany',
    countryCode: 'DE',
    lat: 49.7028,
    lon: 11.9283,
    branch: 'army',
    type: 'camp',
  },
  {
    id: 'hohenfels',
    name: 'Hohenfels Combat Maneuver Training Center',
    country: 'Germany',
    countryCode: 'DE',
    lat: 49.2184,
    lon: 11.8295,
    branch: 'army',
    type: 'camp',
  },
  {
    id: 'mihail-kogalniceanu',
    name: 'Mihail Kogalniceanu Air Base',
    country: 'Romania',
    countryCode: 'RO',
    lat: 44.3622,
    lon: 28.4883,
    branch: 'nato',
    type: 'airfield',
  },
  {
    id: 'graf-ignatievo',
    name: 'Graf Ignatievo Air Base',
    country: 'Bulgaria',
    countryCode: 'BG',
    lat: 42.2900,
    lon: 24.7133,
    branch: 'nato',
    type: 'airfield',
  },

  // ── RUSSIAN ──────────────────────────────────────────────────────────────────
  {
    id: 'ru-main-command-moscow',
    name: 'Russian MoD General Staff HQ',
    country: 'Russia',
    countryCode: 'RU',
    lat: 55.7558,
    lon: 37.6173,
    branch: 'russian',
    type: 'command',
  },
  {
    id: 'severomorsk-naval',
    name: 'Severomorsk Naval Base (Northern Fleet)',
    country: 'Russia',
    countryCode: 'RU',
    lat: 69.0700,
    lon: 33.4200,
    branch: 'russian',
    type: 'naval_base',
  },
  {
    id: 'vladivostok-pacific',
    name: 'Vladivostok Pacific Fleet HQ',
    country: 'Russia',
    countryCode: 'RU',
    lat: 43.1056,
    lon: 131.8797,
    branch: 'russian',
    type: 'naval_base',
  },
  {
    id: 'sevastopol-black-sea',
    name: 'Sevastopol Black Sea Fleet Base',
    country: 'Russia',
    countryCode: 'RU',
    lat: 44.6166,
    lon: 33.5254,
    branch: 'russian',
    type: 'naval_base',
  },
  {
    id: 'kaliningrad-garrison',
    name: 'Kaliningrad Garrison (Baltic Fleet)',
    country: 'Russia',
    countryCode: 'RU',
    lat: 54.7065,
    lon: 20.5111,
    branch: 'russian',
    type: 'installation',
  },
  {
    id: 'engels-2-afb',
    name: 'Engels-2 Air Base',
    country: 'Russia',
    countryCode: 'RU',
    lat: 51.4645,
    lon: 46.1736,
    branch: 'russian',
    type: 'airfield',
  },
  {
    id: 'olenya-ab',
    name: 'Olenya Air Base',
    country: 'Russia',
    countryCode: 'RU',
    lat: 68.1522,
    lon: 33.4631,
    branch: 'russian',
    type: 'airfield',
  },
  {
    id: 'kubinka-afb',
    name: 'Kubinka Air Base',
    country: 'Russia',
    countryCode: 'RU',
    lat: 55.6118,
    lon: 36.6514,
    branch: 'russian',
    type: 'airfield',
  },
  {
    id: 'lipetsk-afb',
    name: 'Lipetsk Air Base',
    country: 'Russia',
    countryCode: 'RU',
    lat: 52.7022,
    lon: 39.5379,
    branch: 'russian',
    type: 'airfield',
  },
  {
    id: '201st-base-tajikistan',
    name: '201st Russian Military Base',
    country: 'Tajikistan',
    countryCode: 'TJ',
    lat: 38.5598,
    lon: 68.7739,
    branch: 'russian',
    type: 'base',
  },
  {
    id: 'gyumri-base-armenia',
    name: '102nd Russian Military Base (Gyumri)',
    country: 'Armenia',
    countryCode: 'AM',
    lat: 40.7892,
    lon: 43.8475,
    branch: 'russian',
    type: 'base',
  },
  {
    id: 'kant-ab-kyrgyzstan',
    name: 'Kant Air Base',
    country: 'Kyrgyzstan',
    countryCode: 'KG',
    lat: 42.8513,
    lon: 74.8461,
    branch: 'russian',
    type: 'airfield',
  },
  {
    id: 'tartus-naval-syria',
    name: 'Tartus Naval Base',
    country: 'Syria',
    countryCode: 'SY',
    lat: 34.8975,
    lon: 35.8661,
    branch: 'russian',
    type: 'naval_base',
  },
  {
    id: 'hmeimim-ab-syria',
    name: 'Hmeimim Air Base',
    country: 'Syria',
    countryCode: 'SY',
    lat: 35.4012,
    lon: 35.9479,
    branch: 'russian',
    type: 'airfield',
  },
  {
    id: 'primorsk-akhtubinsk',
    name: 'Akhtubinsk Flight Test Center',
    country: 'Russia',
    countryCode: 'RU',
    lat: 48.2832,
    lon: 46.1750,
    branch: 'russian',
    type: 'airfield',
  },

  // ── CHINESE ──────────────────────────────────────────────────────────────────
  {
    id: 'western-theater-chengdu',
    name: 'Western Theater Command (Chengdu)',
    country: 'China',
    countryCode: 'CN',
    lat: 30.6598,
    lon: 104.0633,
    branch: 'chinese',
    type: 'command',
  },
  {
    id: 'northern-theater-shenyang',
    name: 'Northern Theater Command (Shenyang)',
    country: 'China',
    countryCode: 'CN',
    lat: 41.8057,
    lon: 123.4315,
    branch: 'chinese',
    type: 'command',
  },
  {
    id: 'eastern-theater-nanjing',
    name: 'Eastern Theater Command (Nanjing)',
    country: 'China',
    countryCode: 'CN',
    lat: 32.0603,
    lon: 118.7969,
    branch: 'chinese',
    type: 'command',
  },
  {
    id: 'southern-theater-guangzhou',
    name: 'Southern Theater Command (Guangzhou)',
    country: 'China',
    countryCode: 'CN',
    lat: 23.1291,
    lon: 113.2644,
    branch: 'chinese',
    type: 'command',
  },
  {
    id: 'djibouti-support-base',
    name: 'PLA Djibouti Support Base',
    country: 'Djibouti',
    countryCode: 'DJ',
    lat: 11.5568,
    lon: 42.8462,
    branch: 'chinese',
    type: 'base',
  },
  {
    id: 'ream-naval-cambodia',
    name: 'Ream Naval Base',
    country: 'Cambodia',
    countryCode: 'KH',
    lat: 10.5234,
    lon: 103.6427,
    branch: 'chinese',
    type: 'naval_base',
  },
  {
    id: 'gwadar-port-pakistan',
    name: 'Gwadar Port',
    country: 'Pakistan',
    countryCode: 'PK',
    lat: 25.1227,
    lon: 62.3255,
    branch: 'chinese',
    type: 'naval_base',
  },
  {
    id: 'woody-island-paracels',
    name: 'Woody Island (Yongxing)',
    country: 'South China Sea',
    countryCode: 'CN',
    lat: 16.8340,
    lon: 112.3370,
    branch: 'chinese',
    type: 'airfield',
  },
  {
    id: 'fiery-cross-reef',
    name: 'Fiery Cross Reef',
    country: 'South China Sea',
    countryCode: 'CN',
    lat: 9.5497,
    lon: 112.8930,
    branch: 'chinese',
    type: 'airfield',
  },
  {
    id: 'mischief-reef',
    name: 'Mischief Reef',
    country: 'South China Sea',
    countryCode: 'CN',
    lat: 9.9042,
    lon: 115.5350,
    branch: 'chinese',
    type: 'installation',
  },
  {
    id: 'subi-reef',
    name: 'Subi Reef',
    country: 'South China Sea',
    countryCode: 'CN',
    lat: 10.9280,
    lon: 114.0830,
    branch: 'chinese',
    type: 'airfield',
  },
  {
    id: 'naval-base-yulin-hainan',
    name: 'Naval Base Yulin (Hainan)',
    country: 'China',
    countryCode: 'CN',
    lat: 18.2253,
    lon: 109.5122,
    branch: 'chinese',
    type: 'naval_base',
  },

  // ── OTHER KEY INSTALLATIONS ───────────────────────────────────────────────────
  {
    id: 'ins-kadamba-karwar',
    name: 'INS Kadamba (Project Seabird)',
    country: 'India',
    countryCode: 'IN',
    lat: 14.7957,
    lon: 74.1190,
    branch: 'navy',
    type: 'naval_base',
  },
  {
    id: 'idf-golan-heights',
    name: 'IDF Golan Heights Command',
    country: 'Israel',
    countryCode: 'IL',
    lat: 33.0079,
    lon: 35.7713,
    branch: 'other',
    type: 'command',
  },
  {
    id: 'camp-lemonnier-djibouti',
    name: 'Camp Lemonnier',
    country: 'Djibouti',
    countryCode: 'DJ',
    lat: 11.5483,
    lon: 43.1483,
    branch: 'multi',
    type: 'camp',
  },
  {
    id: 'jsdf-camp-naha',
    name: 'JSDF Camp Naha (Okinawa)',
    country: 'Japan',
    countryCode: 'JP',
    lat: 26.1954,
    lon: 127.6449,
    branch: 'other',
    type: 'camp',
  },
  {
    id: 'paf-base-minhas',
    name: 'Pakistan Air Force Base Minhas',
    country: 'Pakistan',
    countryCode: 'PK',
    lat: 33.8693,
    lon: 72.4006,
    branch: 'other',
    type: 'airfield',
  },
  {
    id: 'rsaf-king-fahd',
    name: 'King Fahd Air Base',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 21.4793,
    lon: 40.5550,
    branch: 'other',
    type: 'airfield',
  },
  {
    id: 'uae-al-dhafra',
    name: 'Al Dhafra Air Base',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    lat: 24.2480,
    lon: 54.5479,
    branch: 'air_force',
    type: 'base',
  },
];
