export interface NuclearFacility {
  id: string;
  name: string;
  country: string;
  countryCode: string; // ISO Alpha-2
  lat: number;
  lon: number;
  status: 'operational' | 'under_construction' | 'shutdown';
  reactors: number; // number of reactor units
}

export const NUCLEAR_FACILITIES: NuclearFacility[] = [
  // ── United States ──────────────────────────────────────────────────────────
  {
    id: 'palo-verde',
    name: 'Palo Verde Nuclear Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 33.3876,
    lon: -112.8626,
    status: 'operational',
    reactors: 3,
  },
  {
    id: 'peach-bottom',
    name: 'Peach Bottom Atomic Power Station',
    country: 'United States',
    countryCode: 'US',
    lat: 39.7566,
    lon: -76.2686,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'braidwood',
    name: 'Braidwood Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 41.2394,
    lon: -88.2298,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'byron',
    name: 'Byron Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 42.0744,
    lon: -89.2797,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'calvert-cliffs',
    name: 'Calvert Cliffs Nuclear Power Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 38.4317,
    lon: -76.4419,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'clinton',
    name: 'Clinton Power Station',
    country: 'United States',
    countryCode: 'US',
    lat: 40.1592,
    lon: -88.8348,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'columbia',
    name: 'Columbia Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 46.4711,
    lon: -119.3219,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'davis-besse',
    name: 'Davis-Besse Nuclear Power Station',
    country: 'United States',
    countryCode: 'US',
    lat: 41.5980,
    lon: -83.0857,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'diablo-canyon',
    name: 'Diablo Canyon Power Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 35.2113,
    lon: -120.8540,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'donald-c-cook',
    name: 'Donald C. Cook Nuclear Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 41.9761,
    lon: -86.5644,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'dresden',
    name: 'Dresden Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 41.3892,
    lon: -88.2686,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'duane-arnold',
    name: 'Duane Arnold Energy Center',
    country: 'United States',
    countryCode: 'US',
    lat: 42.1006,
    lon: -91.7780,
    status: 'shutdown',
    reactors: 1,
  },
  {
    id: 'fermi',
    name: 'Enrico Fermi Nuclear Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 41.9611,
    lon: -83.2586,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'grand-gulf',
    name: 'Grand Gulf Nuclear Station',
    country: 'United States',
    countryCode: 'US',
    lat: 32.0079,
    lon: -91.0451,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'limerick',
    name: 'Limerick Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 40.2228,
    lon: -75.5841,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'mcguire',
    name: 'McGuire Nuclear Station',
    country: 'United States',
    countryCode: 'US',
    lat: 35.4333,
    lon: -80.9522,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'millstone',
    name: 'Millstone Power Station',
    country: 'United States',
    countryCode: 'US',
    lat: 41.3072,
    lon: -72.1668,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'monticello',
    name: 'Monticello Nuclear Generating Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 45.3328,
    lon: -93.8442,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'nine-mile-point',
    name: 'Nine Mile Point Nuclear Station',
    country: 'United States',
    countryCode: 'US',
    lat: 43.5217,
    lon: -76.4106,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'north-anna',
    name: 'North Anna Power Station',
    country: 'United States',
    countryCode: 'US',
    lat: 38.0644,
    lon: -77.7906,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'oconee',
    name: 'Oconee Nuclear Station',
    country: 'United States',
    countryCode: 'US',
    lat: 34.7919,
    lon: -82.8983,
    status: 'operational',
    reactors: 3,
  },
  {
    id: 'oyster-creek',
    name: 'Oyster Creek Nuclear Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 39.8158,
    lon: -74.2017,
    status: 'shutdown',
    reactors: 1,
  },
  {
    id: 'point-beach',
    name: 'Point Beach Nuclear Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 44.2797,
    lon: -87.5353,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'prairie-island',
    name: 'Prairie Island Nuclear Generating Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 44.6161,
    lon: -92.6314,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'quad-cities',
    name: 'Quad Cities Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 41.7261,
    lon: -90.3328,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'r-e-ginna',
    name: 'R.E. Ginna Nuclear Power Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 43.2794,
    lon: -77.3086,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'river-bend',
    name: 'River Bend Station',
    country: 'United States',
    countryCode: 'US',
    lat: 30.7564,
    lon: -91.3314,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'robinson',
    name: 'H.B. Robinson Nuclear Power Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 34.4008,
    lon: -80.1572,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'salem',
    name: 'Salem Nuclear Power Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 39.4625,
    lon: -75.5369,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'seabrook',
    name: 'Seabrook Station',
    country: 'United States',
    countryCode: 'US',
    lat: 42.8983,
    lon: -70.8497,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'sequoyah',
    name: 'Sequoyah Nuclear Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 35.2261,
    lon: -85.0908,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'south-texas',
    name: 'South Texas Project Nuclear Operating Company',
    country: 'United States',
    countryCode: 'US',
    lat: 28.7953,
    lon: -96.0483,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'st-lucie',
    name: 'St. Lucie Power Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 27.3486,
    lon: -80.2453,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'surry',
    name: 'Surry Power Station',
    country: 'United States',
    countryCode: 'US',
    lat: 37.1650,
    lon: -76.6983,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'susquehanna',
    name: 'Susquehanna Steam Electric Station',
    country: 'United States',
    countryCode: 'US',
    lat: 41.0942,
    lon: -76.1503,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'three-mile-island',
    name: 'Three Mile Island Nuclear Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 40.1533,
    lon: -76.7253,
    status: 'shutdown',
    reactors: 1,
  },
  {
    id: 'turkey-point',
    name: 'Turkey Point Nuclear Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 25.4344,
    lon: -80.3317,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'vogtle',
    name: 'Vogtle Electric Generating Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 33.1428,
    lon: -81.7611,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'watts-bar',
    name: 'Watts Bar Nuclear Plant',
    country: 'United States',
    countryCode: 'US',
    lat: 35.6014,
    lon: -84.7878,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'wolf-creek',
    name: 'Wolf Creek Nuclear Generating Station',
    country: 'United States',
    countryCode: 'US',
    lat: 38.2369,
    lon: -96.0789,
    status: 'operational',
    reactors: 1,
  },

  // ── France ─────────────────────────────────────────────────────────────────
  {
    id: 'flamanville',
    name: 'Flamanville Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 49.5233,
    lon: -1.8808,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'cattenom',
    name: 'Cattenom Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 49.4025,
    lon: 6.2194,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'civaux',
    name: 'Civaux Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 46.4589,
    lon: 0.6542,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'fessenheim',
    name: 'Fessenheim Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 47.9028,
    lon: 7.5664,
    status: 'shutdown',
    reactors: 2,
  },
  {
    id: 'gravelines',
    name: 'Gravelines Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 51.0147,
    lon: 2.1353,
    status: 'operational',
    reactors: 6,
  },
  {
    id: 'nogent-sur-seine',
    name: 'Nogent-sur-Seine Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 48.5156,
    lon: 3.5194,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'paluel',
    name: 'Paluel Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 49.8625,
    lon: 0.6333,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'penly',
    name: 'Penly Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 49.9764,
    lon: 1.2128,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'saint-alban',
    name: 'Saint-Alban Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 45.4058,
    lon: 4.7558,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'tricastin',
    name: 'Tricastin Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 44.3314,
    lon: 4.7331,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'golfech',
    name: 'Golfech Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 44.1061,
    lon: 0.8511,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'belleville-sur-loire',
    name: 'Belleville-sur-Loire Nuclear Power Plant',
    country: 'France',
    countryCode: 'FR',
    lat: 47.5089,
    lon: 2.8733,
    status: 'operational',
    reactors: 2,
  },

  // ── China ──────────────────────────────────────────────────────────────────
  {
    id: 'daya-bay',
    name: 'Daya Bay Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 22.5994,
    lon: 114.5431,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'ling-ao',
    name: 'Ling Ao Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 22.6044,
    lon: 114.5478,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'yangjiang',
    name: 'Yangjiang Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 21.7028,
    lon: 111.6136,
    status: 'operational',
    reactors: 6,
  },
  {
    id: 'taishan',
    name: 'Taishan Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 21.9753,
    lon: 112.8358,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'tianwan',
    name: 'Tianwan Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 34.6858,
    lon: 119.4597,
    status: 'operational',
    reactors: 6,
  },
  {
    id: 'qinshan',
    name: 'Qinshan Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 30.4369,
    lon: 120.9575,
    status: 'operational',
    reactors: 9,
  },
  {
    id: 'fuqing',
    name: 'Fuqing Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 25.4300,
    lon: 119.4083,
    status: 'operational',
    reactors: 6,
  },
  {
    id: 'hongyanhe',
    name: 'Hongyanhe Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 39.7972,
    lon: 121.4833,
    status: 'operational',
    reactors: 6,
  },
  {
    id: 'sanmen',
    name: 'Sanmen Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 29.0994,
    lon: 121.6767,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'haiyang',
    name: 'Haiyang Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 36.8044,
    lon: 121.1478,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'changjiang',
    name: 'Changjiang Nuclear Power Plant',
    country: 'China',
    countryCode: 'CN',
    lat: 19.5153,
    lon: 109.0219,
    status: 'operational',
    reactors: 2,
  },

  // ── Russia ─────────────────────────────────────────────────────────────────
  {
    id: 'balakovo',
    name: 'Balakovo Nuclear Power Plant',
    country: 'Russia',
    countryCode: 'RU',
    lat: 52.0917,
    lon: 47.9478,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'beloyarsk',
    name: 'Beloyarsk Nuclear Power Plant',
    country: 'Russia',
    countryCode: 'RU',
    lat: 56.8431,
    lon: 61.3214,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'bilibino',
    name: 'Bilibino Nuclear Power Plant',
    country: 'Russia',
    countryCode: 'RU',
    lat: 68.0542,
    lon: 166.4361,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'kalinin',
    name: 'Kalinin Nuclear Power Plant',
    country: 'Russia',
    countryCode: 'RU',
    lat: 57.9194,
    lon: 36.7736,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'kola',
    name: 'Kola Nuclear Power Plant',
    country: 'Russia',
    countryCode: 'RU',
    lat: 67.4633,
    lon: 32.4733,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'leningrad',
    name: 'Leningrad Nuclear Power Plant',
    country: 'Russia',
    countryCode: 'RU',
    lat: 59.8858,
    lon: 29.0744,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'novovoronezh',
    name: 'Novovoronezh Nuclear Power Plant',
    country: 'Russia',
    countryCode: 'RU',
    lat: 51.2228,
    lon: 39.2119,
    status: 'operational',
    reactors: 5,
  },
  {
    id: 'smolensk',
    name: 'Smolensk Nuclear Power Plant',
    country: 'Russia',
    countryCode: 'RU',
    lat: 54.1547,
    lon: 33.2272,
    status: 'operational',
    reactors: 3,
  },
  {
    id: 'rostov',
    name: 'Rostov Nuclear Power Plant',
    country: 'Russia',
    countryCode: 'RU',
    lat: 47.5769,
    lon: 42.1483,
    status: 'operational',
    reactors: 4,
  },

  // ── Japan ──────────────────────────────────────────────────────────────────
  {
    id: 'kashiwazaki-kariwa',
    name: 'Kashiwazaki-Kariwa Nuclear Power Plant',
    country: 'Japan',
    countryCode: 'JP',
    lat: 37.4283,
    lon: 138.6003,
    status: 'operational',
    reactors: 7,
  },
  {
    id: 'sendai',
    name: 'Sendai Nuclear Power Plant',
    country: 'Japan',
    countryCode: 'JP',
    lat: 31.8347,
    lon: 130.1894,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'ikata',
    name: 'Ikata Nuclear Power Plant',
    country: 'Japan',
    countryCode: 'JP',
    lat: 33.4944,
    lon: 132.3117,
    status: 'operational',
    reactors: 3,
  },
  {
    id: 'takahama',
    name: 'Takahama Nuclear Power Plant',
    country: 'Japan',
    countryCode: 'JP',
    lat: 35.5247,
    lon: 135.5006,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'ohi',
    name: 'Ohi Nuclear Power Plant',
    country: 'Japan',
    countryCode: 'JP',
    lat: 35.5442,
    lon: 135.6558,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'tomari',
    name: 'Tomari Nuclear Power Plant',
    country: 'Japan',
    countryCode: 'JP',
    lat: 43.0517,
    lon: 140.5181,
    status: 'operational',
    reactors: 3,
  },

  // ── South Korea ────────────────────────────────────────────────────────────
  {
    id: 'kori',
    name: 'Kori Nuclear Power Plant',
    country: 'South Korea',
    countryCode: 'KR',
    lat: 35.3244,
    lon: 129.2906,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'hanbit',
    name: 'Hanbit Nuclear Power Plant',
    country: 'South Korea',
    countryCode: 'KR',
    lat: 35.4144,
    lon: 126.4158,
    status: 'operational',
    reactors: 6,
  },
  {
    id: 'hanul',
    name: 'Hanul Nuclear Power Plant',
    country: 'South Korea',
    countryCode: 'KR',
    lat: 37.0944,
    lon: 129.3836,
    status: 'operational',
    reactors: 6,
  },
  {
    id: 'wolsong',
    name: 'Wolsong Nuclear Power Plant',
    country: 'South Korea',
    countryCode: 'KR',
    lat: 35.7119,
    lon: 129.4758,
    status: 'operational',
    reactors: 4,
  },

  // ── India ──────────────────────────────────────────────────────────────────
  {
    id: 'kakrapar',
    name: 'Kakrapar Atomic Power Station',
    country: 'India',
    countryCode: 'IN',
    lat: 21.2361,
    lon: 73.3511,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'kudankulam',
    name: 'Kudankulam Nuclear Power Plant',
    country: 'India',
    countryCode: 'IN',
    lat: 8.1714,
    lon: 77.7133,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'madras',
    name: 'Madras Atomic Power Station',
    country: 'India',
    countryCode: 'IN',
    lat: 12.5519,
    lon: 80.1719,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'narora',
    name: 'Narora Atomic Power Station',
    country: 'India',
    countryCode: 'IN',
    lat: 28.1761,
    lon: 78.3919,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'tarapur',
    name: 'Tarapur Atomic Power Station',
    country: 'India',
    countryCode: 'IN',
    lat: 19.8317,
    lon: 72.6528,
    status: 'operational',
    reactors: 4,
  },

  // ── United Kingdom ─────────────────────────────────────────────────────────
  {
    id: 'hinkley-point-b',
    name: 'Hinkley Point B Nuclear Power Station',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.2094,
    lon: -3.1319,
    status: 'shutdown',
    reactors: 2,
  },
  {
    id: 'sizewell-b',
    name: 'Sizewell B Nuclear Power Station',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 52.2083,
    lon: 1.6197,
    status: 'operational',
    reactors: 1,
  },
  {
    id: 'torness',
    name: 'Torness Nuclear Power Station',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 55.9672,
    lon: -2.4483,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'heysham',
    name: 'Heysham Nuclear Power Station',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 54.0275,
    lon: -2.9183,
    status: 'operational',
    reactors: 4,
  },

  // ── Switzerland ────────────────────────────────────────────────────────────
  {
    id: 'beznau',
    name: 'Beznau Nuclear Power Plant',
    country: 'Switzerland',
    countryCode: 'CH',
    lat: 47.5233,
    lon: 8.1133,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'leibstadt',
    name: 'Leibstadt Nuclear Power Plant',
    country: 'Switzerland',
    countryCode: 'CH',
    lat: 47.5997,
    lon: 8.1833,
    status: 'operational',
    reactors: 1,
  },

  // ── Czech Republic ─────────────────────────────────────────────────────────
  {
    id: 'dukovany',
    name: 'Dukovany Nuclear Power Plant',
    country: 'Czech Republic',
    countryCode: 'CZ',
    lat: 49.0881,
    lon: 16.1478,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'temelin',
    name: 'Temelin Nuclear Power Plant',
    country: 'Czech Republic',
    countryCode: 'CZ',
    lat: 49.1811,
    lon: 14.3744,
    status: 'operational',
    reactors: 2,
  },

  // ── Hungary ────────────────────────────────────────────────────────────────
  {
    id: 'paks',
    name: 'Paks Nuclear Power Plant',
    country: 'Hungary',
    countryCode: 'HU',
    lat: 46.5736,
    lon: 18.8561,
    status: 'operational',
    reactors: 4,
  },

  // ── Finland ────────────────────────────────────────────────────────────────
  {
    id: 'loviisa',
    name: 'Loviisa Nuclear Power Plant',
    country: 'Finland',
    countryCode: 'FI',
    lat: 60.4056,
    lon: 26.3569,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'olkiluoto',
    name: 'Olkiluoto Nuclear Power Plant',
    country: 'Finland',
    countryCode: 'FI',
    lat: 61.2353,
    lon: 21.4444,
    status: 'operational',
    reactors: 3,
  },

  // ── Romania ────────────────────────────────────────────────────────────────
  {
    id: 'cernavoda',
    name: 'Cernavoda Nuclear Power Plant',
    country: 'Romania',
    countryCode: 'RO',
    lat: 44.3261,
    lon: 28.0564,
    status: 'operational',
    reactors: 2,
  },

  // ── Bulgaria ───────────────────────────────────────────────────────────────
  {
    id: 'kozloduy',
    name: 'Kozloduy Nuclear Power Plant',
    country: 'Bulgaria',
    countryCode: 'BG',
    lat: 43.7933,
    lon: 23.7836,
    status: 'operational',
    reactors: 2,
  },

  // ── Slovakia ───────────────────────────────────────────────────────────────
  {
    id: 'mochovce',
    name: 'Mochovce Nuclear Power Plant',
    country: 'Slovakia',
    countryCode: 'SK',
    lat: 48.4208,
    lon: 18.5283,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'bohunice',
    name: 'Bohunice Nuclear Power Plant',
    country: 'Slovakia',
    countryCode: 'SK',
    lat: 48.4933,
    lon: 17.6819,
    status: 'shutdown',
    reactors: 2,
  },

  // ── Slovenia ───────────────────────────────────────────────────────────────
  {
    id: 'krsko',
    name: 'Krsko Nuclear Power Plant',
    country: 'Slovenia',
    countryCode: 'SI',
    lat: 45.8286,
    lon: 15.5100,
    status: 'operational',
    reactors: 1,
  },

  // ── Armenia ────────────────────────────────────────────────────────────────
  {
    id: 'metsamor',
    name: 'Metsamor Nuclear Power Plant',
    country: 'Armenia',
    countryCode: 'AM',
    lat: 40.1819,
    lon: 44.1447,
    status: 'operational',
    reactors: 1,
  },

  // ── Iran ───────────────────────────────────────────────────────────────────
  {
    id: 'bushehr',
    name: 'Bushehr Nuclear Power Plant',
    country: 'Iran',
    countryCode: 'IR',
    lat: 28.8294,
    lon: 50.8869,
    status: 'operational',
    reactors: 1,
  },

  // ── Ukraine ────────────────────────────────────────────────────────────────
  {
    id: 'khmelnitsky',
    name: 'Khmelnitsky Nuclear Power Plant',
    country: 'Ukraine',
    countryCode: 'UA',
    lat: 50.3036,
    lon: 26.6497,
    status: 'operational',
    reactors: 2,
  },
  {
    id: 'south-ukraine-npp',
    name: 'South Ukraine Nuclear Power Plant',
    country: 'Ukraine',
    countryCode: 'UA',
    lat: 47.8303,
    lon: 31.2197,
    status: 'operational',
    reactors: 3,
  },
  {
    id: 'rivne-npp',
    name: 'Rivne Nuclear Power Plant',
    country: 'Ukraine',
    countryCode: 'UA',
    lat: 51.3264,
    lon: 25.8908,
    status: 'operational',
    reactors: 4,
  },
  {
    id: 'zaporizhzhia-npp',
    name: 'Zaporizhzhia Nuclear Power Plant',
    country: 'Ukraine',
    countryCode: 'UA',
    lat: 47.5092,
    lon: 34.5853,
    status: 'operational',
    reactors: 6,
  },
  {
    id: 'chernobyl',
    name: 'Chernobyl Nuclear Power Plant',
    country: 'Ukraine',
    countryCode: 'UA',
    lat: 51.3890,
    lon: 30.0997,
    status: 'shutdown',
    reactors: 4,
  },
];
